"""Renamed month columns

Revision ID: 6f04c7f905a4
Revises: 
Create Date: 2024-12-30 08:54:15.943176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f04c7f905a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_usage')
    op.drop_table('usage_data')
    with op.batch_alter_table('telecom_usage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('telecom_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('usage_data',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('2023-01', mysql.FLOAT(), nullable=True),
    sa.Column('2023-02', mysql.FLOAT(), nullable=True),
    sa.Column('2023-03', mysql.FLOAT(), nullable=True),
    sa.Column('2023-04', mysql.FLOAT(), nullable=True),
    sa.Column('2023-05', mysql.FLOAT(), nullable=True),
    sa.Column('2023-06', mysql.FLOAT(), nullable=True),
    sa.Column('2023-07', mysql.FLOAT(), nullable=True),
    sa.Column('2023-08', mysql.FLOAT(), nullable=True),
    sa.Column('2023-09', mysql.FLOAT(), nullable=True),
    sa.Column('2023-10', mysql.FLOAT(), nullable=True),
    sa.Column('2023-11', mysql.FLOAT(), nullable=True),
    sa.Column('2023-12', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_usage',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('2023-01', mysql.FLOAT(), nullable=True),
    sa.Column('2023-02', mysql.FLOAT(), nullable=True),
    sa.Column('2023-03', mysql.FLOAT(), nullable=True),
    sa.Column('2023-04', mysql.FLOAT(), nullable=True),
    sa.Column('2023-05', mysql.FLOAT(), nullable=True),
    sa.Column('2023-06', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
